=== PMSFIT/fmi-ls-ref/main/schema/fmi3LayeredStandardReferenceManifest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fmi-ls="http://fmi-standard.org/fmi-ls-manifest" elementFormDefault="qualified" attributeFormDefault="qualified">
	<xs:import namespace="http://fmi-standard.org/fmi-ls-manifest" schemaLocation="https://raw.githubusercontent.com/modelica/fmi-standard/main/schema/fmi3LayeredStandardManifest.xsd"/>
	<xs:annotation>
		<xs:documentation>
Copyright(c) 2023 Modelica Association Project "FMI".
             All rights reserved.

This file is licensed by the copyright holders under the 2-Clause BSD License
(https://opensource.org/licenses/BSD-2-Clause):

----------------------------------------------------------------------------
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

- Redistributions of source code must retain the above copyright notice,
 this list of conditions and the following disclaimer.

- Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
----------------------------------------------------------------------------
        </xs:documentation>
	</xs:annotation>
	<xs:element name="fmiReferences">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Experiment" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Parameters" minOccurs="0" type="TParameters"/>
							<xs:element name="Stimuli" minOccurs="0" type="TTimeSeriesData"/>
							<xs:element name="References" minOccurs="0" type="TTimeSeriesData"/>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="description" type="xs:string"/>
						<xs:attribute name="startTime" type="xs:double"/>
						<xs:attribute name="stopTime" type="xs:double"/>
						<xs:attribute name="tolerance" type="xs:double"/>
						<xs:attribute name="stepSize" type="xs:double"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Related" minOccurs="0" maxOccurs="unbounded" type="TRelated"/>
			</xs:sequence>
			<xs:attribute ref="fmi-ls:fmi-ls-name" use="required" fixed="org.fmi-standard.fmi-ls-ref"/>
			<xs:attribute ref="fmi-ls:fmi-ls-version" use="required"/>
			<xs:attribute ref="fmi-ls:fmi-ls-description" use="required" fixed="Layered Standard providing reference stimuli and results for an FMU."/>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="TRelated">
		<xs:attribute name="type" type="xs:string" use="optional" default="application/octet-stream">
			<xs:annotation>
				<xs:documentation xml:lang="en">
					This attribute specifies the MIME type of the related resource, which
					defaults to application/octet-stream to indicate arbitrary binary data.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="source" type="xs:anyURI" use="required">
			<xs:annotation>
				<xs:documentation xml:lang="en">
					This attribute indicates the source of the related resource as a URI
					(cf. RFC 3986).  For purposes of the resolution of relative URIs
					the base URI is the URI of the fmiReference file.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="role" use="required">
			<xs:annotation>
				<xs:documentation xml:lang="en">
					This attribute specifies the role of the related resource.
				</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
                    <xs:enumeration value="document"/>
                    <xs:enumeration value="requirement"/>
                    <xs:enumeration value="specification"/>
                    <xs:enumeration value="model"/>
                    <xs:enumeration value="parameter"/>
                    <xs:enumeration value="system"/>
                    <xs:enumeration value="testcase"/>
                    <xs:enumeration value="result"/>
                    <xs:enumeration value="method"/>
                    <xs:enumeration value="rationale"/>
                    <xs:enumeration value="report"/>
                    <xs:enumeration value="request"/>
                    <xs:enumeration value="delivery"/>
                    <xs:enumeration value="executable"/>
                    <xs:enumeration value="configuration"/>
                    <xs:enumeration value="other"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="description" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="TParameters">
		<xs:attribute name="type" type="xs:string" use="optional" default="application/x-ssp-parameter-set">
			<xs:annotation>
				<xs:documentation xml:lang="en">
					This attribute specifies the MIME type of the parameter data source, which
					defaults to application/x-ssp-parameter-set to indicate the SSV file format
					as specified in the SSP standard. No further types are currently defined, 
					but can of course be added at a later date.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="source" type="xs:anyURI" use="required">
			<xs:annotation>
				<xs:documentation xml:lang="en">
					This attribute indicates the source of the parameter source as a URI
					(cf. RFC 3986).  For purposes of the resolution of relative URIs
					the base URI is the URI of the fmiReference file.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="TTimeSeriesData">
		<xs:attribute name="type" type="xs:string" use="optional" default="text/csv">
			<xs:annotation>
				<xs:documentation xml:lang="en">
					This attribute specifies the MIME type of the time series data source, which
					defaults to text/csv to indicate the CSV file format as specified in XXX.
					No further types are currently defined, but can of course be added at a later
					date, e.g. for pre-existing time series file formats, like HDF5, MDF, etc.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="source" type="xs:anyURI" use="required">
			<xs:annotation>
				<xs:documentation xml:lang="en">
					This attribute indicates the source of the time series data as a URI
					(cf. RFC 3986).  For purposes of the resolution of relative URIs
					the base URI is the URI of the fmiReference file.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== PMSFIT/fmi-ls-ref/docs/examples/fmi_ls_ref_manifest_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<fmiReferences
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../schema/fmi3LayeredStandardReferenceManifest.xsd"
	xmlns:fmi-ls="http://fmi-standard.org/fmi-ls-manifest"
	fmi-ls:fmi-ls-name="org.fmi-standard.fmi-ls-ref"
	fmi-ls:fmi-ls-version="1.0.0-rc.1"
	fmi-ls:fmi-ls-description="Layered Standard providing reference stimuli and results for an FMU.">
	
	<Experiment name="Test1" description="Baseline steady-state test"
		startTime="0.0" stopTime="10.0" stepSize="0.001" tolerance="0.004">
		<Stimuli source="test1-in.csv"/>
		<References source="test1-ref.csv"/>
	</Experiment>
	<Experiment name="Test2" description="Baseline dynamic test" startTime="0.0" stopTime="15.0" stepSize="0.010">
		<Parameters source="dynamic-params.ssv"/>
		<Stimuli source="test2-in.csv"/>
		<References source="test2-ref.hdf5" type="application/hdf5"/>
	</Experiment>
	<Related type="text/modelica" source="modelica/mymodel.mo" role="model" description="Modelica Model Source"/>
</fmiReferences>
